apiVersion: v1
items:
- apiVersion: policies.kyverno.io/v1
  kind: ImageValidatingPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"policies.kyverno.io/v1","kind":"ImageValidatingPolicy","metadata":{"annotations":{},"name":"verify-supply-chain-demo"},"spec":{"attestors":[{"cosign":{"ctlog":{"url":"https://rekor.sigstore.dev"},"keyless":{"identities":[{"issuer":"https://token.actions.githubusercontent.com","subject":"https://github.com/adeola2021/phase3-devsecops/.github/workflows/security.yml@refs/heads/main"}]}},"name":"githubCosign"}],"matchImageReferences":[{"glob":"ghcr.io/adeola2021/*"}],"validationActions":["Audit","Deny"],"validationConfigurations":{"mutateDigest":true,"required":true,"verifyDigest":true},"validations":[{"expression":"images.containers.map(\n  image,\n  verifyImageSignatures(image, [attestors.githubCosign])\n).all(result, result \u003e 0)","message":"Image signature verification failed."}]}}
    creationTimestamp: "2026-08-03T16:11:17Z"
    generation: 1
    name: verify-supply-chain-demo
    resourceVersion: "104388"
    uid: 69dcf2bd-0ee4-4c8b-a528-bda2c8bca4db
  spec:
    attestors:
    - cosign:
        ctlog:
          url: https://rekor.sigstore.dev
        keyless:
          identities:
          - issuer: https://token.actions.githubusercontent.com
            subject: https://github.com/adeola2021/phase3-devsecops/.github/workflows/security.yml@refs/heads/main
      name: githubCosign
    matchImageReferences:
    - glob: ghcr.io/adeola2021/*
    validationActions:
    - Audit
    - Deny
    validationConfigurations:
      mutateDigest: true
      required: true
      verifyDigest: true
    validations:
    - expression: |-
        images.containers.map(
          image,
          verifyImageSignatures(image, [attestors.githubCosign])
        ).all(result, result > 0)
      message: Image signature verification failed.
  status:
    autogen: {}
    conditionStatus:
      conditions:
      - lastTransitionTime: "2026-08-03T16:11:17Z"
        message: Webhook configured.
        reason: Succeeded
        status: "True"
        type: WebhookConfigured
      - lastTransitionTime: "2026-08-03T16:11:17Z"
        message: Policy is ready for reporting.
        reason: Succeeded
        status: "True"
        type: RBACPermissionsGranted
      message: ""
      ready: true
kind: List
metadata:
  resourceVersion: ""
