name: SLSA Provenance

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

      digest:
        required: true
        type: string

jobs:

  provenance:

    permissions:
      actions: read
      id-token: write
      contents: read
      packages: write

    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0

    with:
      image: ${{ inputs.image }}
      digest: ${{ inputs.digest }}
